---
- name: Ansible Example
  hosts: all
  become: true
  remote_user: root

  tasks:

  - name: Update
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install python3-pip
    ansible.builtin.apt:
      name: python3-pip
      state: present

  - name: Run installation script
    command: python3 -m pip install -r /vagrant/requirements.txt

  - name: export app.py
    command: export FLASK_APP=/vagrant/app.py

  - name: Execute flask run
    command: python3 -m flask run --host=0.0.0.0




