version: '3.7'
services:
  devops:
    container_name: devops
    image: tomaszkania2000/pipeliners:latest
    ports:
      - '5000:5000'
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/config.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - devops